language: android
branches:
  only:
    - master
    - develop

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

script:
  - ./gradlew :retroauth:build